import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body>
         <header style={
        {
          backgroundColor:"aqua",
          padding:"2rem"
        }
      }>
             Header
      </header>
      <main>
        {children}
      </main>
        
         <footer style={
        {
          backgroundColor:"olive",
          padding:"2rem"
        }
      }>
        Footer    
      </footer>
      </body>
     
    </html>
  );
}
