import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default:"This is a default value",
    template:" %s | next js",
    absolute:"",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
