"use client"
import Link from "next/link";
import { usePathname } from "next/navigation";
import "./globals.css";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const path = usePathname();
  return (
    <html lang="en">
      <body>
         <header>
         <nav>
          <Link href="/" className={ path === "/" ? "active" : ""}>Home</Link>
          <Link href="/product" className={ path === "/product" ? "active" : ""}>product</Link>
          <Link href="/contact" className={ path === "/contact" ? "active" : ""}>contact</Link>
        </nav>
      </header>
        {children}
      </body>
    </html>
  );
}
